### ISSUE TITLE
googlesearch plugin

### ISSUE THREAD

**Issue by cneira** [LightTable/plugin-metadata#11]
{:name "google-search"
 :version "0.0.1"
 :author "cnb"
 :source "https://github.com/cneira/googlesearch"
 :desc "makes available google, github,amazon and grooveshark web search "
 :behaviors "googlesearch.behaviors"}

**Comment by cldwalker** [comment]
Nice! I'd been meaning to write something like this but you beat me to it :) Can you git tag your repo with the version as explained in [the readme](https://github.com/LightTable/plugin-metadata#submit-a-plugin)? That's needed to detect the plugin

**Comment by cneira** [comment]
Done!
