### ISSUE TITLE
0.0.1 of Link with editor

### ISSUE THREAD

**Issue by obarbeau** [LightTable/plugin-metadata#14]
Hi, could you please add

{:name "Link with editor"
 :version "0.0.1"
 :author "Olivier Barbeau <olivier.barbeau@gmail.com>"
 :source "https://github.com/obarbeau/lt-link-with-editor"
 :desc "Light Table plugin for linking the file currently edited with the workspace view."
 :behaviors "link-with-editor.behaviors"}

**Comment by obarbeau** [comment]
Sorry I forgot to include JS file. I've recreated the repo. This is now corrected.

**Comment by cldwalker** [comment]
Plugin added. Fwiw, you can distribute css with your plugin by [adding this behavior](https://github.com/LightTable/LightTable/wiki/FAQ#how-do-i-load-custom-css-files-at-startup) and pointing to a relative path.

**Comment by obarbeau** [comment]
Thank you for the tip! I will soon update.
