### ISSUE TITLE
lt_snippets renamed to Snippets and upped version

### ISSUE THREAD

**Issue by rundis** [LightTable/plugin-metadata#18]
I have changed the lt_snippets plugin name to Snippets.
https://github.com/rundis/lt-snippets

A new 0.1.0 release [here](https://github.com/rundis/lt-snippets/releases/tag/0.1.0)

I guess we need to remove the lt_snippets entry so that it doesn't appear in the plugin manager, or do you have a better solution to handle the rename AND allowing for a smooth upgrade for existing users ?

**Comment by cldwalker** [comment]
For a plugin rename we rename the old directory name to the new one. This removes the old lt_snippets entry and existing users need to uninstall lt_snippets and install Snippets. I did this in https://github.com/LightTable/plugin-metadata/commit/6274159ec84ed3f58bcd30709e72207e67455917

**Comment by cldwalker** [comment]
For an example of a plugin that has already done this see Julia

**Comment by rundis** [comment]
Tx !
