### ISSUE TITLE
AsciiLight - version 0.2.0

### ISSUE THREAD

**Issue by rundis** [LightTable/plugin-metadata#21]
https://github.com/rundis/AsciiLight/releases/tag/0.2.0

cheers
Magnus

**Comment by rundis** [comment]
Would it be more convenient if i submitted a pull request ? (or even got commit rights :) )

**Comment by cldwalker** [comment]
I'd be happy to give you commit rights on this repo but I can't without making you a committer on all Light Table projects - [screenshot](https://www.dropbox.com/s/khlebcfs93f212q/Screenshot%202015-02-20%2009.20.55.png?dl=0) . 
@ibdknox Any chance you could give me that ability? That would require making me a LightTable admin or just giving me admin rights for this repo. Or you could just add @rundis to this repo

**Comment by cldwalker** [comment]
@rundis I've released your plugin in the meantime and will leave this open till you get commit rights

**Comment by ibdknox** [comment]
Weird, it claims all the committers have admin rights:
![image](https://cloud.githubusercontent.com/assets/70036/6289268/c31ffee2-b8d3-11e4-877d-e415418644cd.png)

@rundis added to committers :)

**Comment by rundis** [comment]
Cool ! thx.

**Comment by cldwalker** [comment]
@ibdknox Yeah. I see the same description. I guess committers have admin rights in the sense they can add/remove to the committers team but we can't add/remove individuals to specific repos. I guess this is only an owner right. Not a big deal but something to keep in mind.
@rundis Welcome aboard :) Most of what you need to know is in [the readme](https://github.com/LightTable/plugin-metadata#for-committers)

**Comment by ibdknox** [comment]
@cldwalker I added you and @joshuafcole to owners, so you two should be able to do anything I can at this point.

**Comment by cldwalker** [comment]
@ibdknox Thanks
