### ISSUE TITLE
Update the Stylus to v0.0.3

### ISSUE THREAD

**Issue by dmitrykiselyov** [LightTable/plugin-metadata#27]
Update the [Stylus](https://github.com/hashobject/lt-stylus) to v0.0.3
Thanks!

**Comment by cldwalker** [comment]
You forgot to tag 0.0.3 in your repo as explained in the readme. I can release once you tag

**Comment by podviaznikov** [comment]
Done: https://github.com/hashobject/lt-stylus/tree/0.0.3
