### ISSUE TITLE
0.1.10 of Lt-TernJS

### ISSUE THREAD

**Issue by Armaklan** [LightTable/plugin-metadata#31]
New release of TernJs plugin which fix it on recent LightTable.

{:name "TernJS",
 :version "0.1.10",
 :author "Eric Pritchett",
 :source "https://github.com/mortalapeman/LT-TernJS",
 :desc
 "Provides intelligent auto-complete, inline docs and jump to definition for JavaScript files in Light Table.",
 :behaviors "ternjs.behaviors",
 :dependencies {:Javascript "0.0.1"}}

**Comment by kenny-evitt** [comment]
@Armaklan can you submit a pull request for this?

**Comment by Armaklan** [comment]
Done.

**Comment by kenny-evitt** [comment]
@Armaklan thanks!
