### ISSUE TITLE
Better CoffeeScript Syntax Support

### ISSUE THREAD

**Issue by huaoguo** [LightTable/plugin-metadata#33]
{:name "CoffeeScriptSyntax"
 :version "0.0.1"
 :author "huaoguo"
 :source "https://github.com/huaoguo/lt-coffee-script-syntax"
 :desc "Better CoffeeScript syntax"
 :behaviors "coffee_script.behaviors"}

**Comment by kenny-evitt** [comment]
@huaoguo Please submit a PR for this.

**Comment by ohAitch** [comment]
README.md should probably be updated from `To submit a plugin, open an issue and provide the plugin's github url and the version to release e.g. 0.1.2. Your plugin's repository must be tagged with the requested version.`

**Comment by kenny-evitt** [comment]
@ohAitch Good point. I made [an issue for the change](https://github.com/LightTable/plugin-metadata/issues/34). Care to submit a PR? :)
