### ISSUE TITLE
Update README instructions to ask for a PR to be submitted for new or updated plugins

### ISSUE THREAD

**Issue by kenny-evitt** [LightTable/plugin-metadata#34]
[This comment](https://github.com/LightTable/plugin-metadata/issues/33#issuecomment-131275751) was the source of this change.

**Comment by ohAitch** [comment]
Does the "For Committers" section turn into official submission instructions?

**Comment by kenny-evitt** [comment]
@ohAitch Yeah; 'committers' will just be those that merge the PRs.

**Comment by cldwalker** [comment]
Closing as users don't consistently use the provided script/submit-plugin.rb which can lead to placing plugins in the wrong directory or submitting a plugin without pushing its git tag. Latest misplacement is https://github.com/LightTable/plugin-metadata/pull/38. Another example is https://github.com/LightTable/plugin-metadata/pull/7
