### ISSUE TITLE
PHP 0.0.1

### ISSUE THREAD

**Issue by thierrymarianne** [LightTable/plugin-metadata#36]
https://github.com/thierrymarianne/LightTable-PHP/releases/tag/0.0.1

Cheers,

**Comment by cldwalker** [comment]
Merci!

**Comment by kenny-evitt** [comment]
@thierrymarianne Awesome work – thanks! Want us to announce this on the blog or the Google Groups group? [I just linked to your repo on a thread in the Groups group about PHP support.](https://groups.google.com/d/msg/light-table-discussion/M6hRjrL-XYE/8_gFJg8OCwAJ)

**Comment by thierrymarianne** [comment]
@cldwalker Merci ! ^_^  

@kenny-evitt Sure thing, it is far from being complete in comparison to what exists for other languages but it is the very first step before having more sophisticated code evaluation (provided PHP 7 deploy new mechanisms [to replace fatal errors with exceptions](https://wiki.php.net/rfc/engine_exceptions_for_php7), I believe the timing is perfect to play around with the new language capabilities).
