### ISSUE TITLE
Kudamono Theme

### ISSUE THREAD

**Issue by zachstone** [LightTable/plugin-metadata#41]
{:name "Kudamono Theme"
 :version "0.0.1"
 :author "Zach Stone"
 :source "https://github.com/zachstone/kudamono-lighttable-theme"
 :desc "A very colorful theme designed for Clojure."
 :behaviors "kudamono.behaviors"}

Thanks! And is this what everyone has to do?

**Comment by cldwalker** [comment]
Thanks! "Everyone has to do" meaning how do you request a submission? Per [the readme](https://github.com/LightTable/plugin-metadata#submit-a-plugin), submitting a url and version is all we need

**Comment by cldwalker** [comment]
To distribute the plugin I'll need you to git tag 0.0.1. Not seeing any tags for your plugin

**Comment by zachstone** [comment]
I was just asking if this is the process everyone goes through to submit a plugin, but I assume it is. And I saw that I only needed those 2 items, but noticed that most others were pasting the entire `plugin.edn`. Anyways, I added the 0.0.1 tag. Thanks again.

**Comment by cldwalker** [comment]
Ah gotcha. Released. Look forward to trying out your theme
