### ISSUE TITLE
Parinfer plugin

### ISSUE THREAD

**Issue by mauricioszabo** [LightTable/plugin-metadata#45]
{:name "Parinfer"
 :version "0.0.1"
 :author "Maurício Szabo"
 :source "https://github.com/mauricioszabo/lt-parinfer"
 :desc "parinfer port for LigtTable"
 :behaviors "lt-parinfer.behaviors"}

Initial version of parinfer plugin.

**Comment by cldwalker** [comment]
Nice work. I see :source should be https://github.com/mauricioszabo/lt_parinfer. Can you fix that in your plugin.edn and retag 0.0.1?

**Comment by mauricioszabo** [comment]
Ok, re-tagged. Thanks for helping!

**Comment by cldwalker** [comment]
Released. To answer one of your readme questions, there isn't a way to deactivate the plugin currently though we may consider it down the road in https://github.com/LightTable/LightTable/issues/1993
