### ISSUE TITLE
New release of AltTab plugin

### ISSUE THREAD

**Issue by eldargab** [LightTable/plugin-metadata#49]
Please include version 0.2.1 of [AltTab](https://github.com/eldargab/LT-AltTab) plugin.

**Comment by kenny-evitt** [comment]
@eldargab Mind submitting a PR with the change?

**Comment by cldwalker** [comment]
@kenny-evitt Normally we should do it as explained in https://github.com/LightTable/plugin-metadata/issues/34#issuecomment-160353173

**Comment by kenny-evitt** [comment]
@cldwalker Hopefully I'll remember next time :smile:
