### ISSUE TITLE
new plugin - playground

### ISSUE THREAD

**Issue by carocad** [LightTable/plugin-metadata#55]
hey guys,
could you please add my new plugin: `playground v0.0.1`
URL: https://github.com/carocad/playground

thanks

PS: I created the plugin with the intention of putting it in the wiki/README of Lighttable so that people can learn from it. Please let me know your thoughts on this.

**Comment by rundis** [comment]
tx. It gives an exception on startup though. I'm guessing because baby steps is part of the compiled source, but haven't spent any time looking into it.

**Comment by carocad** [comment]
@rundis thanks a lot. I am still fairly new to Clojurescript so I didn't have those errors when I was running the plugin (without installing it).
BTW, your guess was right. The expressions in baby_steps were being evaluated at compile time, causing some errors. I updated the plugin and will open a new issue with the new version
