### ISSUE TITLE
New plugin: lt-lint

### ISSUE THREAD

**Issue by bbbates** [LightTable/plugin-metadata#61]
{:name "Linting"
 :version "0.0.4"
 :author "Brendan Bates"
 :source "https://github.com/bbbates/lt-lint"
 :desc "Base plugin for enabling editor linter addons for LightTable"
 :behaviors "lt_lint.behaviors"}

**Comment by rundis** [comment]
Cool, I'll see if I could use this for https://github.com/rundis/elm-light. I looked at the Codemirror plugin, but ended up creating a custom impl for my plugin. Might revisit that decision :-)

**Comment by bbbates** [comment]
Yes, definitely give it a go! 

I was contemplating rolling my own for the lt-clojure-linter plugin, but the lint cm addon covered off pretty much everything I needed (once I found you could lint asynchronously!).
