### ISSUE TITLE
New plugin: lt-jshint

### ISSUE THREAD

**Issue by bbbates** [LightTable/plugin-metadata#62]
{:name "lt-jshint"
 :version "0.0.3"
 :author "Brendan Bates"
 :source "https://github.com/bbbates/lt-jshint"
 :desc "JSHINT Linting for Javascript files"
 :behaviors "lt_jshint.behaviors"
 :dependencies {"Linting" "0.0.3"}}

**Comment by rundis** [comment]
Any reason this doesn't depend on 0.0.4 of the base plugin ? Just curious.

**Comment by bbbates** [comment]
Good find...just an oversight (will fix in the next release). 
LT seems to not care if you have a later version of the dependent plugin....or does it?
