### ISSUE TITLE
New plugin: lt-eslint

### ISSUE THREAD

**Issue by bbbates** [LightTable/plugin-metadata#73]
{:name "lt-eslint"
 :version "0.0.1"
 :author "Brendan Bates"
 :source "https://github.com/bbbates/lt-eslint"
 :desc "ESLint for Lighttable"
 :behaviors "lt_eslint.behaviors" 
 :dependencies {"Linting" "0.0.5"}}

**Comment by cldwalker** [comment]
Nice!

**Comment by Mouvedia** [comment]
@bbbates could you provide a step by step installation process in your README?
cf bbbates/lt-eslint#2
